export const dashboardPage = {
  pt: {
    "dashboard-page.greeting": "Saudações",
    "dashboard-page.lastMonth": "Último mês",
    "dashboard-page.totalClients": "Total de Clientes",
    "dashboard-page.clients": "Clientes",
    "dashboard-page.totalClientsNumber": "Número total de Clientes",
    "dashboard-page.users": "Usuários",
    "dashboard-page.totalUsers": "Total de Usuários",
    "dashboard-page.totalUsersNumber": "Número total de Usuários",
    "dashboard-page.operators": "Operadores",
    "dashboard-page.totalOperators": "Total de Operadores",
    "dashboard-page.totalOperatorsNumber": "Número total de Operadores",
    "dashboard-page.activity": "Atividade",
    "dashboard-page.activityOverview": "Visão geral das atividades",
    "dashboard-page.filesCreated": "Arquivos criados",
    "dashboard-page.foldersCreated": "Pastas criadas",
    "dashboard-page.actionsOverview": "Visão geral das ações",
    "dashboard-page.folderFileCreation": "Criação de pastas e arquivos",
    "dashboard-page.recentTransactions": "Transações Recentes",
    "dashboard-page.manageTransactions": "Gerencie suas transações recentes",
    "dashboard-page.filterById": "Filtrar por ID...",
    "dashboard-page.columns": "Colunas",
    "dashboard-page.id": "ID",
    "dashboard-page.date": "Data",
    "dashboard-page.price": "Preço",
    "dashboard-page.openMenu": "Abrir menu",
    "dashboard-page.transactionsFound": "transações encontradas.",
    "dashboard-page.transactionsNotFound": "Nenhum resultado encontrado...",
    "dashboard-page.previous": "Anterior",
    "dashboard-page.next": "Próximo",
    "dashboard-page.copyId": "Copiar ID",
  },
  en: {
    "dashboard-page.transactionsNotFound": "No results found...",
    "dashboard-page.greeting": "Greetings",
    "dashboard-page.lastMonth": "Last month",
    "dashboard-page.totalClients": "Total Clients",
    "dashboard-page.clients": "Clients",
    "dashboard-page.totalClientsNumber": "Total number of Clients",
    "dashboard-page.users": "Users",
    "dashboard-page.totalUsers": "Total Users",
    "dashboard-page.totalUsersNumber": "Total number of Users",
    "dashboard-page.operators": "Operators",
    "dashboard-page.totalOperators": "Total Operators",
    "dashboard-page.totalOperatorsNumber": "Total number of Operators",
    "dashboard-page.activity": "Activity",
    "dashboard-page.activityOverview": "Activity Overview",
    "dashboard-page.filesCreated": "Files Created",
    "dashboard-page.foldersCreated": "Folders Created",
    "dashboard-page.actionsOverview": "Actions Overview",
    "dashboard-page.folderFileCreation": "Folder and File Creation",
    "dashboard-page.recentTransactions": "Recent Transactions",
    "dashboard-page.manageTransactions": "Manage your recent transactions",
    "dashboard-page.filterById": "Filter by ID...",
    "dashboard-page.columns": "Columns",
    "dashboard-page.id": "ID",
    "dashboard-page.date": "Date",
    "dashboard-page.price": "Price",
    "dashboard-page.openMenu": "Open Menu",
    "dashboard-page.transactionsFound": "transactions found.",
    "dashboard-page.previous": "Previous",
    "dashboard-page.next": "Next",
    "dashboard-page.copyId": "Copy ID",
  },
};
