export const organizationPage = {
  pt: {
    "organization-page.editOrganization": "Editar dados da organização",
    "organization-page.managePermissions": "Gerenciar permissões",
    "organization-page.deleteOrganization": "Deletar conta do cliente",
    "organization-page.storage": "Armazenamento",
    "organization-page.selectOperator": "Escolha um operador",
    "organization-page.enterNewName": "Insira um novo nome (opcional)",
    "organization-page.searchFolders": "Pesquisar pastas",
    "organization-page.newFolderName": "Novo nome da pasta",
    "organization-page.users": "Usuarios",
    "organization-page.accountDetails": "Detalhes da conta",
    "organization-page.allFolders": "Todas as Pastas",
    "organization-page.allFiles": "Todas as Pastas",
    "organization-page.myFolders": "Minhas Pastas",
    "organization-page.selectFoldersAndFiles": "select folders and files",
    "organization-page.selectFolderToStart": "Selecione uma pasta para começar",
    "organization-page.chooseFolder":
      "Escolha uma pasta no menu lateral para ver seus arquivos",
    "organization-page.searchIn": "search in",
    "organization-page.assignOrRemovePermissions":
      "Atribuir ou remover permissões",
    "organization-page.name": "Nome",
    "organization-page.chooseOperator": "Escolha um operador",
    "organization-page.allowUpload": "Permitir upload de arquivos nesta pasta",
    "organization-page.allowDownload":
      "Permitir download de arquivos nesta pasta",
    "organization-page.save": "Salvar",
    "organization-page.uploadFiles": "Carregar Arquivos",
    "organization-page.checkingPermissions": "Verificando permissões...",
    "organization-page.noPermission": "Você não tem permissão para acessar esta pasta.",
    "organization-page.emptyFolder": "Esta pasta está vazia",
    "organization-page.emptyFolderHelper": "Adicione arquivos ou crie novas pastas para começar.",
    "organization-page.search": "Buscar",
    "organization-page.noFileChosen": "Nenhum arquivo selecionado",
    "organization-page.dragAndDrop":
      "Arraste e solte arquivos aqui, ou clique para selecionar",
    "organization-page.proceedWithUpload": "Prosseguir com o Upload",
    "organization-page.originalName": "Nome original:",
    "organization-page.deleteFolder": "Deletar pasta",
    "organization-page.deleteFolderConfirmation":
      "Tem certeza que deseja apagar a pasta?",
    "organization-page.deleteFolderWarning":
      "Esta ação não pode ser desfeita. Isso excluirá permanentemente esta pasta e removerá seus dados de nossos servidores.",
    "organization-page.delete": "Deletar",
    "organization-page.deleteFile": "Deletar arquivo",
    "organization-page.deleteFileConfirmation":
      "Tem certeza que deseja apagar o arquivo?",
    "organization-page.deleteFileWarning":
      "Esta ação não pode ser desfeita. Isso excluirá permanentemente este arquivo de nossos servidores.",
    "organization-page.folderName": "Nome da pasta",
    "organization-page.settings": "Configurações",
    "organization-page.manageProfile":
      "Gerencie o perfil e configurações aqui.",
    "organization-page.emailAddress": "Endereço de E-Mail",
    "organization-page.currentPlan": "Plano Atual",
    "organization-page.accountStatus": "Estado da conta",
    "organization-page.accountActive": "Ativada",
    "organization-page.accountInactive": "Desativada",
    "organization-page.deactivate": "Desativar",
    "organization-page.activate": "Ativar",
    "organization-page.paymentCalendar": "Calendario de pagamento",
    "organization-page.makePayment": "Efectuar pagamento",
    "organization-page.accountData": "Dados da Conta",
    "organization-page.updateAccountInfo": "Atualizar informações da conta",
    "organization-page.editInfo": "Editar informações",
    "organization-page.recentTransactions": "Recent Transactions",
    "organization-page.manageTransactions":
      "Gerenciar suas transações recentes",
    "organization-page.filterById": "Filtrar por ID...",
    "organization-page.columns": "Colunas",
    "organization-page.id": "ID",
    "organization-page.date": "Data",
    "organization-page.price": "Preço",
    "organization-page.openMenu": "Abrir menu",
    "organization-page.transactionsFound": "transações encontradas.",
    "organization-page.previous": "Anterior",
    "organization-page.next": "Próximo",
    "organization-page.registerPayment": "Efetuar registro de pagamento",
    "organization-page.basicInfo": "Informações Básicas",
    "organization-page.plan": "Plano",
    "organization-page.selectPlan": "Selecione um plano",
    "organization-page.gigabytes": "Gibabytes",
    "organization-page.confirmation": "Confirmação",
    "organization-page.confirmPaymentRegistration":
      "Tem certeza que quer realizar o registro de pagamento para o plano: ",
    "organization-page.create": "Criar",
    "organization-page.create-folder-dialog.title": "Criar nova pasta",
    "organization-page.create-folder-dialog.description":
      "Digite um nome para sua nova pasta.",
    "organization-page.create-folder-dialog.placeholder": "Nome da pasta",
    "organization-page.create-folder-dialog.cancel": "Cancelar",
    "organization-page.create-folder-dialog.create": "Criar",
    "organization-page.delete-file-dialog-description":
      "Isso excluirá permanentemente o arquivo e todos os seus dados. Essa ação não pode ser desfeita.",
    "organization-page.confirmDelete": "Tem certeza que deseja apagar a conta?",
    "organization-page.deleteWarning":
      "Esta ação não pode ser desfeita. Isso excluirá permanentemente esta conta e removerá seus dados de nossos servidores.",
    "search-dialog.no-results": "Nenhum resultado encontrado.",
    "search-dialog.enter-chars": "Digite pelo menos 3 caracteres para pesquisar.",
    "search-dialog.title": "Pesquisar na pasta",
    "search-dialog.placeholder": "Pesquisar por arquivos e pastas...",

  },
  en: {
    "organization-page.storage": "Storage",
    "organization-page.managePermissions": "Gerenciar Permissions",
    "organization-page.deleteOrganization": "Delete client account",
    "organization-page.editOrganization": "Edit client data",
    "organization-page.selectOperator": "Select an operator",
    "organization-page.searchFolders": "Search folders",
    "organization-page.enterNewName": "Enter a new name (optional)",
    "organization-page.newFolderName": "New folder name",
    "organization-page.users": "Users",
    "organization-page.accountDetails": "Account Details",
    "organization-page.allFolders": "All Folders",
    "organization-page.allFiles": "All Files",
    "organization-page.myFolders": "My Folders",
    "organization-page.selectFoldersAndFiles": "select folders and files",
    "organization-page.selectFolderToStart": "Select a folder to start",
    "organization-page.chooseFolder":
      "Choose a folder in the sidebar to view your files",
    "organization-page.searchIn": "search in",
    "organization-page.assignOrRemovePermissions":
      "Assign or remove permissions",
    "organization-page.name": "Name",
    "organization-page.chooseOperator": "Choose an operator",
    "organization-page.allowUpload": "Allow file upload in this folder",
    "organization-page.allowDownload": "Allow file download in this folder",
    "organization-page.save": "Save",
    "organization-page.uploadFiles": "Upload Files",
    "organization-page.checkingPermissions": "Checking permissions...",
    "organization-page.noPermission": "You do not have permission to access this folder.",
    "organization-page.emptyFolder": "This folder is empty",
    "organization-page.emptyFolderHelper": "Add files or create new folders to get started.",
    "organization-page.search": "Search",
    "organization-page.noFileChosen": "No file chosen",
    "organization-page.dragAndDrop":
      "Drag and drop files here, or click to select",
    "organization-page.proceedWithUpload": "Proceed with Upload",
    "organization-page.originalName": "Original name:",
    "organization-page.deleteFolder": "Delete folder",
    "organization-page.deleteFolderConfirmation":
      "Are you sure you want to delete this folder?",
    "organization-page.deleteFolderWarning":
      "This action cannot be undone. It will permanently delete this folder and remove its data from our servers.",
    "organization-page.delete": "Delete",
    "organization-page.deleteFile": "Delete file",
    "organization-page.deleteFileConfirmation":
      "Are you sure you want to delete this file?",
    "organization-page.deleteFileWarning":
      "This action cannot be undone. It will permanently delete this file from our servers.",
    "organization-page.folderName": "Folder name",
    "organization-page.settings": "Settings",
    "organization-page.manageProfile": "Manage profile and settings here.",
    "organization-page.emailAddress": "Email Address",
    "organization-page.currentPlan": "Current Plan",
    "organization-page.accountStatus": "Account Status",
    "organization-page.accountActive": "Active",
    "organization-page.accountInactive": "Inactive",
    "organization-page.deactivate": "Deactivate",
    "organization-page.activate": "Activate",
    "organization-page.paymentCalendar": "Payment Calendar",
    "organization-page.makePayment": "Make Payment",
    "organization-page.accountData": "Account Data",
    "organization-page.updateAccountInfo": "Update account information",
    "organization-page.editInfo": "Edit information",
    "organization-page.recentTransactions": "Recent Transactions",
    "organization-page.manageTransactions": "Manage your recent transactions",
    "organization-page.filterById": "Filter by ID...",
    "organization-page.columns": "Columns",
    "organization-page.id": "ID",
    "organization-page.date": "Date",
    "organization-page.price": "Price",
    "organization-page.openMenu": "Open menu",
    "organization-page.transactionsFound": "Transactions found.",
    "organization-page.previous": "Previous",
    "organization-page.next": "Next",
    "organization-page.registerPayment": "Register Payment",
    "organization-page.basicInfo": "Basic Information",
    "organization-page.plan": "Plan",
    "organization-page.selectPlan": "Select a plan",
    "organization-page.gigabytes": "Gigabytes",
    "organization-page.confirmation": "Confirmation",
    "organization-page.confirmPaymentRegistration":
      "Are you sure you want to register payment for the plan:",
    "organization-page.create": "Create",
    "organization-page.create-folder-dialog.title": "Create new folder",
    "organization-page.create-folder-dialog.description":
      "Enter a name for your new folder.",
    "organization-page.create-folder-dialog.placeholder": "Folder name",
    "organization-page.create-folder-dialog.cancel": "Cancel",
    "organization-page.create-folder-dialog.create": "Create",
    "organization-page.delete-file-dialog-description":
      "This will permanently delete the file and all its data. This action cannot be undone.",
    "organization-page.confirmDelete":
      "Are you sure you want to delete this account?",
    "organization-page.deleteWarning":
      "This action cannot be undone. It will permanently delete this account and remove its data from our servers.",
    "search-dialog.no-results": "No results found.",
    "search-dialog.enter-chars": "Enter at least 3 characters to search.",
    "search-dialog.title": "Search in Folder",
    "search-dialog.placeholder": "Search for files and folders...",

  },
};
