export const organizationsPage = {
  pt: {
    "organizations-page.title": "Clientes",
    "organizations-page.created": "Criados",
    "organizations-page.no-clients-warning":
      "Não há Clientes disponíveis. Por favor, adicione um novo Cliente.",
    "organizations-page.description": "Gerencie todos os Clientes do sistema",
    "organizations-page.total": "Total de Clientes",
    "organizations-page.uploadFiles": "Carregar de arquivos",
    "organizations-page.totalNumber": "numero total de Clientes",
    "organizations-page.createdThisMonth": "Criados neste mês",
    "organizations-page.createdThisMonthDescription":
      "Clientes criados neste mês",
    "organizations-page.createdLastMonth": "Criados no mês passado",
    "organizations-page.createdLastMonthDescription":
      "Clientes criados no mês passado",
    "organizations-page.manageDescription":
      "Gerencie todos os Clientes do sistema",
    "organizations-page.search": "Buscar Cliente...",
    "organizations-page.columns": "Colunas",
    "organizations-page.id": "ID",
    "organizations-page.name": "Nome",
    "organizations-page.email": "Email",
    "organizations-page.nextPayment": "Proximo pagamento",
    "organizations-page.status": "Estado",
    "organizations-page.days": "dias",
    "organizations-page.active": "Ativado",
    "organizations-page.inactive": "Desativado",
    "organizations-page.openMenu": "Abrir menu",
    "organizations-page.found": "Clientes encontradas.",
    "organizations-page.previous": "Anterior",
    "organizations-page.next": "Próximo",
    "organizations-page.history": "Histórico de Criação",
    "organizations-page.historyDescription":
      "Acompanhe o crescimento dos Clientes ao longo do tempo",
    "organizations-page.last": "Ultimos",
    "organizations-page.visibleColumns": "Colunas Visíveis",
    "organizations-page.months": "meses",
    "organizations-page.addClient": "Adicionar Cliente",
    "organizations-page.basicInfo": "Informações Básicas",
    "organizations-page.clientName": "Nome do Cliente",
    "organizations-page.clientType": "Tipo",
    "organizations-page.selectType": "Selecione o tipo",
    "organizations-page.plan": "Plano",
    "organizations-page.selectPlan": "Selecione um plano",
    "organizations-page.contact": "Contato",
    "organizations-page.phone": "Telefone",
    "organizations-page.address": "Endereço",
    "organizations-page.city": "Cidade",
    "organizations-page.state": "Estado",
    "organizations-page.nuit": "Nuit",
    "organizations-page.continue": "Continuar",
    "organizations-page.adminData": "Dados do admin",
    "organizations-page.firstName": "Primeiro nome",
    "organizations-page.lastName": "Ultimo nome",
    "organizations-page.adminEmail": "Email",
    "organizations-page.adminPhone": "Telefone",
    "organizations-page.create": "Criar",
  },
  en: {
    "organizations-page.no-clients-warning":
      "There are no Clients available. Please add a new Customer.",
    "organizations-page.title": "Clients",
    "organizations-page.created": "Created",
    "organizations-page.description": "Manage all Clients in the system",
    "organizations-page.total": "Total Clients",
    "organizations-page.uploadFiles": "Upload Files",
    "organizations-page.totalNumber": "total number of Clients",
    "organizations-page.createdThisMonth": "Created this month",
    "organizations-page.createdThisMonthDescription":
      "Clients created this month",
    "organizations-page.createdLastMonth": "Created last month",
    "organizations-page.createdLastMonthDescription":
      "Clients created last month",
    "organizations-page.manageDescription": "Manage all Clients in the system",
    "organizations-page.search": "Search Client...",
    "organizations-page.columns": "Columns",
    "organizations-page.id": "ID",
    "organizations-page.name": "Name",
    "organizations-page.email": "Email",
    "organizations-page.nextPayment": "Next payment",
    "organizations-page.status": "Status",
    "organizations-page.days": "days",
    "organizations-page.active": "Active",
    "organizations-page.inactive": "Inactive",
    "organizations-page.openMenu": "Open menu",
    "organizations-page.found": "Clients found.",
    "organizations-page.previous": "Previous",
    "organizations-page.next": "Next",
    "organizations-page.history": "Creation History",
    "organizations-page.historyDescription":
      "Track the growth of Clients over time",
    "organizations-page.last": "Last",
    "organizations-page.visibleColumns": "Visible Columns",
    "organizations-page.months": "months",
    "organizations-page.addClient": "Add Client",
    "organizations-page.basicInfo": "Basic Information",
    "organizations-page.clientName": "Client Name",
    "organizations-page.clientType": "Type",
    "organizations-page.selectType": "Select type",
    "organizations-page.plan": "Plan",
    "organizations-page.selectPlan": "Select a plan",
    "organizations-page.contact": "Contact",
    "organizations-page.phone": "Phone",
    "organizations-page.address": "Address",
    "organizations-page.city": "City",
    "organizations-page.state": "State",
    "organizations-page.nuit": "Nuit",
    "organizations-page.continue": "Continue",
    "organizations-page.adminData": "Admin Data",
    "organizations-page.firstName": "First Name",
    "organizations-page.lastName": "Last Name",
    "organizations-page.adminEmail": "Email",
    "organizations-page.adminPhone": "Phone",
    "organizations-page.create": "Create",
  },
};
