export const usersPage = {
  pt: {
    "users-page.title": "Usuarios",
    "users-page.add": "Adicionar +",
    "users-page.total": "Total de usuarios",
    "users-page.registered": "usuarios cadastrados",
    "users-page.totalAdmins": "Total de usuarios administradores",
    "users-page.admins": "usuarios administradores",
    "users-page.totalNonAdmins": "Total de usuarios não administradores",
    "users-page.nonAdmins": "usuarios não administradores",
    "users-page.filterUsers": "Filtrar usuarios...",
    "users-page.columns": "Colunas",
    "users-page.id": "Id",
    "users-page.name": "Nome",
    "users-page.email": "Email",
    "users-page.status": "Estado",
    "users-page.role": "Papel",
    "users-page.active": "Ativado",
    "users-page.inactive": "Desativado",
    "users-page.openMenu": "Abrir menu",
    "users-page.admin": "Admin",
    "users-page.user": "usuario",
    "users-page.previous": "Anterior",
    "users-page.next": "Proximo",
    "users-page.addNewUser": "Adicionar novo usuario",
    "users-page.firstName": "Primeiro nome",
    "users-page.firstNamePlaceholder": "Digite o primeiro nome",
    "users-page.lastName": "Último nome",
    "users-page.lastNamePlaceholder": "Digite o último nome",
    "users-page.emailPlaceholder": "Digite o email",
    "users-page.phone": "Telefone",
    "users-page.phonePlaceholder": "Digite o telefone",
    "users-page.userRole": "Usuario",
    "users-page.create": "Criar",
  },
  en: {
    "users-page.title": "Users",
    "users-page.add": "Add +",
    "users-page.total": "Total users",
    "users-page.registered": "registered users",
    "users-page.totalAdmins": "Total admin users",
    "users-page.admins": "admin users",
    "users-page.totalNonAdmins": "Total non-admin users",
    "users-page.nonAdmins": "non-admin users",
    "users-page.filterUsers": "Filter users...",
    "users-page.columns": "Columns",
    "users-page.id": "Id",
    "users-page.name": "Name",
    "users-page.email": "Email",
    "users-page.status": "Status",
    "users-page.role": "Role",
    "users-page.active": "Active",
    "users-page.inactive": "Inactive",
    "users-page.openMenu": "Open menu",
    "users-page.admin": "Admin",
    "users-page.user": "user",
    "users-page.previous": "Previous",
    "users-page.next": "Next",
    "users-page.addNewUser": "Add new user",
    "users-page.firstName": "First Name",
    "users-page.firstNamePlaceholder": "Enter first name",
    "users-page.lastName": "Last Name",
    "users-page.lastNamePlaceholder": "Enter last name",
    "users-page.emailPlaceholder": "Enter email",
    "users-page.phone": "Phone",
    "users-page.phonePlaceholder": "Enter phone",
    "users-page.userRole": "User",
    "users-page.create": "Create",
  },
};
